services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=ct648
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./pokemon-battle-backend
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: ct648
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build:
      context: ./pokemon-battle-front
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - backend

volumes:
  postgres_data: